version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql_server_db
    environment:
      - ENV=develop
      - BASE_PATH=/crisis
      - HOST=http://localhost
      - PORT=3000
      - DB_HOST=sql_server_db
      - DB_PASSWORD=ReallyStrongPassword123
    ports:
      - '3000:3000'
      - '9229:9229'

  sql_server_db:
    image: microsoft/mssql-server-linux:2017-latest
    logging:
      driver: none
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ReallyStrongPassword123
    ports:
      - 1433:1433
