version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sql_server_db
    environment:
      - BASE_PATH=/crisis
      - HOST=http://localhost
      - PORT=3000
      - DB_HOST=sql_server_db
      - DB_PORT=1433
      - DB_PASSWORD=reallyStrongPwd123
      - DB_USER=sa
      - DB_CONNECTOR_MIGRATIONS=mssql
      - DB_CONNECTOR=mssql
      - DB_NAME=crisis
    ports:
      - '3000:3000'
      - '9229:9229'

  sql_server_db:
    image: microsoft/mssql-server-linux
    logging:
      driver: none
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - 1433
