openapi: '3.0.0'
info:
  version: 0.0.1
  title: Crisis
  description: Crisis Microservice
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Jigsaw XYZ 1.0
    url: https://www.jigsaw.xyz/license-v1.html
servers:
  - url: http://api.crisis.jigsaw.xyz/v1
paths:
  /priority:
    get:
      description: Returns the grant for a specific priority permission
      operationId: get priority permission grant
      parameters:
        - $ref: '#/components/parameters/xCorrelationId'
        - $ref: '#/components/parameters/bearerAuthentication'
        - $ref: '#/components/parameters/mobileNumberPathParameter'
        - $ref: '#/components/parameters/priorityPermissionPathParameter'
      responses:
        '200':
          description: Priority Permissions Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionsResponse'
        '401':
          description: Priority Permissions Unauthorised Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorisedError'
        '404':
          description: 404 - Not Found Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Priority Permissions Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        default:
          description: Priority Permissions Invalid Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
components:
  parameters:
    xCorrelationId:
      name: x-correlation-id
      required: true
      in: header
      description: Correlation ID required for log tracing.
      schema:
        type: string
        format: uuid
    xTenantNamespace:
      name: x-tenant-namespace
      required: true
      in: header
      description: Tenant identity.
      schema:
        type: string
    bearerAuthentication:
      name: Authorization
      required: true
      in: header
      description: Authorisation header
      schema:
        type: string
        format: jwt
    mobileNumberPathParameter:
      name: mobileNumber
      required: true
      in: query
      description: Mobile Number
      schema:
        type: string
    priorityPermissionPathParameter:
      name: priorityPermission
      required: true
      in: query
      description: Priority Permission from Enum
      schema:
        type: string
  schemas:
    PermissionsResponse:
      title: Permission Response
      additionalProperties: false
      required:
        - permission
      properties:
        permission:
          type: object
          additionalProperties: false
          required:
            - grant
            - priority
          properties:
            grant:
              type: string
            priority:
              type: boolean
    NotFoundError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    UnauthorisedError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InvalidRequestError:
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InternalServerError:
      title: Internal Server Error
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
