openapi: '3.0.0'
info:
  version: 0.0.1
  title: Crisis
  description: Crisis Microservice
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Jigsaw XYZ 1.0
    url: https://www.jigsaw.xyz/license-v1.html
servers:
  - url: http://api.crisis.jigsaw.xyz/v1
paths:
  /priority:
    get:
      description: Returns the grant for a specific priority grant
      operationId: get priority grant
      parameters:
        - $ref: '#/components/parameters/xCorrelationId'
        - $ref: '#/components/parameters/bearerAuthentication'
        - $ref: '#/components/parameters/mobileNumberPathParameter'
        - $ref: '#/components/parameters/priorityGrantPathParameter'
      responses:
        '200':
          description: Priority Grants Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriorityResponse'
        '401':
          description: Priority Grants Unauthorised Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorisedError'
        '404':
          description: 404 - Not Found Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Priority Grants Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        default:
          description: Priority Grants Invalid Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
components:
  parameters:
    xCorrelationId:
      name: x-correlation-id
      required: true
      in: header
      description: Correlation ID required for log tracing.
      schema:
        type: string
        format: uuid
    xTenantNamespace:
      name: x-tenant-namespace
      required: true
      in: header
      description: Tenant identity.
      schema:
        type: string
    bearerAuthentication:
      name: Authorization
      required: true
      in: header
      description: Authorisation header
      schema:
        type: string
        format: jwt
    mobileNumberPathParameter:
      name: mobileNumber
      required: true
      in: query
      description: Mobile Number
      schema:
        type: string
    priorityGrantPathParameter:
      name: priorityGrant
      required: true
      in: query
      description: Priority Grant from Enum
      schema:
        type: string
  schemas:
    PriorityResponse:
      title: Priority Response
      additionalProperties: false
      required:
        - priority
        - valid
      properties:
        priority:
          type: string
          example: 'food::delivery'
        valid:
          type: boolean
    NotFoundError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    UnauthorisedError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InvalidRequestError:
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InternalServerError:
      title: Internal Server Error
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
